<?php
$item=$this->item;
$this->headTitle($item->GetTitle());
$this->headMeta()->appendName('keywords', $item->GetKeywords());
$this->headMeta()->appendName('description', $item->GetDescription() );
?>
<div class="article-entry">
	<h1><?=$item->getCaption();?></h1>
	<div class="entry-body1">
	<?=$item->getFull();?>
	</div>
</div>
<script type="text/javascript" src="//yastatic.net/es5-shims/0.0.2/es5-shims.min.js" charset="utf-8"></script>
<script type="text/javascript" src="//yastatic.net/share2/share.js" charset="utf-8"></script>
<div class="ya-share2" data-services="vkontakte,facebook,odnoklassniki,moimir,gplus,twitter,viber,whatsapp" data-counter=""></div>
<br />
<a href="<?=$this->url("stream_".$this->locale,["stream"=>$item->getCategory()]);?>">Перейти к списку</a>
